### ISSUE TITLE
websocket-polyfill problem

### ISSUE THREAD

**Issue by pailakapo** [hzrd149/blossom-server#2]
Installing from docker and from source I get an error.

Docker:

```
# docker run -v blossom_data:/app/data -v $(pwd)/config.yml:/app/config.yml -p 3000:3000 ghcr.io/hzrd149/blossom-server:master

Unable to find image 'ghcr.io/hzrd149/blossom-server:master' locally
master: Pulling from hzrd149/blossom-server
4abcf2066143: Pull complete 
7231dd947546: Pull complete 
58ec58ffa356: Pull complete 
853d72f1314b: Pull complete 
c2c363068bce: Pull complete 
5b77f188786e: Pull complete 
90feb962d4b7: Pull complete 
cee29b128def: Pull complete 
8ce2194a071b: Pull complete 
50793f4c7b48: Pull complete 
7da88de86e03: Pull complete 
Digest: sha256:fede0235753aebbb469aacfc0f61751e95b663ce3c2d8e01c9df387c4f63cd78
Status: Downloaded newer image for ghcr.io/hzrd149/blossom-server:master
/app/node_modules/websocket-polyfill/lib/index.js:8
    (_a = (_b = global).WebSocket) !== null && _a !== void 0 ? _a : (_b.WebSocket = (0, import2_1.default)("ws"));
                                                                                                          ^

TypeError: (0 , import2_1.default) is not a function
    at Object.<anonymous> (/app/node_modules/websocket-polyfill/lib/index.js:8:107)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.13.1
```

Source:

`# yarn start
yarn run v1.22.22
$ node build/index.js
/mnt/user/blossom/blossom-server/node_modules/websocket-polyfill/lib/index.js:8
    (_a = (_b = global).WebSocket) !== null && _a !== void 0 ? _a : (_b.WebSocket = (0, import2_1.default)("ws"));
                                                                                                          ^

TypeError: (0 , import2_1.default) is not a function
    at Object.<anonymous> (/mnt/user/blossom/blossom-server/node_modules/websocket-polyfill/lib/index.js:8:107)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.13.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by pailakapo** [comment]
Still got the error:

docker run -v blossom_data:/app/data -v $(pwd)/config.yml:/app/config.yml -p 3000:3000 ghcr.io/hzrd149/blossom-server:master
/app/node_modules/websocket-polyfill/lib/index.js:8
    (_a = (_b = global).WebSocket) !== null && _a !== void 0 ? _a : (_b.WebSocket = (0, import2_1.default)("ws"));
                                                                                                          ^

TypeError: (0 , import2_1.default) is not a function
    at Object.<anonymous> (/app/node_modules/websocket-polyfill/lib/index.js:8:107)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.13.1
